# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crpcs/clientService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spinnerTypes import transaction_pb2 as spinnerTypes_dot_transaction__pb2
from spinnerTypes import block_pb2 as spinnerTypes_dot_block__pb2
from spinnerTypes import client_pb2 as spinnerTypes_dot_client__pb2
from spinnerTypes import utils_pb2 as spinnerTypes_dot_utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='crpcs/clientService.proto',
  package='proto.crpcs.clientService',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x63rpcs/clientService.proto\x12\x19proto.crpcs.clientService\x1a\x1espinnerTypes/transaction.proto\x1a\x18spinnerTypes/block.proto\x1a\x19spinnerTypes/client.proto\x1a\x18spinnerTypes/utils.proto2\xd7\x04\n\rClientService\x12\x38\n\x07writeTx\x12\x18.proto.types.Transaction\x1a\x11.proto.types.TxID\"\x00\x12\x38\n\x06readTx\x12\x12.proto.types.TxReq\x1a\x18.proto.types.Transaction\"\x00\x12\x37\n\x08txStatus\x12\x12.proto.types.TxReq\x1a\x15.proto.types.TxStatus\"\x00\x12\x38\n\treadBlock\x12\x15.proto.types.BlockReq\x1a\x12.proto.types.Block\"\x00\x12\x37\n\tgetHeight\x12\x12.proto.types.Empty\x1a\x14.proto.types.Integer\"\x00\x12\x33\n\x07isAlive\x12\x12.proto.types.Empty\x1a\x12.proto.types.Empty\"\x00\x12\x36\n\x08poolSize\x12\x12.proto.types.Empty\x1a\x14.proto.types.Integer\"\x00\x12\x39\n\x0bpendingSize\x12\x12.proto.types.Empty\x1a\x14.proto.types.Integer\"\x00\x12>\n\rgetValidators\x12\x12.proto.types.Empty\x1a\x17.proto.types.Validators\"\x00\x12>\n\rgetConfigInfo\x12\x12.proto.types.Empty\x1a\x17.proto.types.ConfigInfo\"\x00\x42*\n\x19proto.crpcs.clientServiceB\rclientServiceb\x06proto3')
  ,
  dependencies=[spinnerTypes_dot_transaction__pb2.DESCRIPTOR,spinnerTypes_dot_block__pb2.DESCRIPTOR,spinnerTypes_dot_client__pb2.DESCRIPTOR,spinnerTypes_dot_utils__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031proto.crpcs.clientServiceB\rclientService'))
# @@protoc_insertion_point(module_scope)
