# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spinnerTypes/meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spinnerTypes/meta.proto',
  package='proto.types',
  syntax='proto3',
  serialized_pb=_b('\n\x17spinnerTypes/meta.proto\x12\x0bproto.types\"7\n\x04Meta\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x0b\n\x03\x63id\x18\x02 \x01(\x05\x12\x11\n\tcidSeries\x18\x03 \x01(\x05\x42\x13\n\x0bproto.typesB\x04metab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_META = _descriptor.Descriptor(
  name='Meta',
  full_name='proto.types.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='proto.types.Meta.channel', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='proto.types.Meta.cid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cidSeries', full_name='proto.types.Meta.cidSeries', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['Meta'] = _META

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'spinnerTypes.meta_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.Meta)
  ))
_sym_db.RegisterMessage(Meta)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013proto.typesB\004meta'))
# @@protoc_insertion_point(module_scope)
