# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spinnerTypes/block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spinnerTypes import meta_pb2 as spinnerTypes_dot_meta__pb2
from spinnerTypes import transaction_pb2 as spinnerTypes_dot_transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spinnerTypes/block.proto',
  package='proto.types',
  syntax='proto3',
  serialized_pb=_b('\n\x18spinnerTypes/block.proto\x12\x0bproto.types\x1a\x17spinnerTypes/meta.proto\x1a\x1espinnerTypes/transaction.proto\"#\n\x07\x42lockID\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0b\n\x03\x62id\x18\x02 \x01(\x05\"\xcf\x01\n\x0b\x42lockHeader\x12\x1c\n\x01m\x18\x01 \x01(\x0b\x32\x11.proto.types.Meta\x12\x0c\n\x04prev\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x17\n\x0ftransactionHash\x18\x04 \x01(\x0c\x12\r\n\x05proof\x18\x05 \x01(\t\x12!\n\x03\x62id\x18\x06 \x01(\x0b\x32\x14.proto.types.BlockID\x12\r\n\x05\x65mpty\x18\x07 \x01(\x08\x12*\n\x03hst\x18\x08 \x01(\x0b\x32\x1d.proto.types.HeaderStatistics\"g\n\x10HeaderStatistics\x12\x13\n\x0bproposeTime\x18\x01 \x01(\x03\x12\x15\n\rtentativeTime\x18\x02 \x01(\x03\x12\x14\n\x0c\x64\x65\x66initeTime\x18\x03 \x01(\x03\x12\x11\n\ttentative\x18\x05 \x01(\x08\"&\n\x0f\x42lockStatistics\x12\x13\n\x0bproposeTime\x18\x01 \x01(\x03\"\xa6\x01\n\x05\x42lock\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.proto.types.BlockHeader\x12 \n\x02id\x18\x02 \x01(\x0b\x32\x14.proto.types.BlockID\x12&\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x18.proto.types.Transaction\x12)\n\x03\x62st\x18\x04 \x01(\x0b\x32\x1c.proto.types.BlockStatisticsB\x14\n\x0bproto.typesB\x05\x62lockb\x06proto3')
  ,
  dependencies=[spinnerTypes_dot_meta__pb2.DESCRIPTOR,spinnerTypes_dot_transaction__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLOCKID = _descriptor.Descriptor(
  name='BlockID',
  full_name='proto.types.BlockID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='proto.types.BlockID.pid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid', full_name='proto.types.BlockID.bid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=133,
)


_BLOCKHEADER = _descriptor.Descriptor(
  name='BlockHeader',
  full_name='proto.types.BlockHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='proto.types.BlockHeader.m', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prev', full_name='proto.types.BlockHeader.prev', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='proto.types.BlockHeader.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transactionHash', full_name='proto.types.BlockHeader.transactionHash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proof', full_name='proto.types.BlockHeader.proof', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid', full_name='proto.types.BlockHeader.bid', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='empty', full_name='proto.types.BlockHeader.empty', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hst', full_name='proto.types.BlockHeader.hst', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=343,
)


_HEADERSTATISTICS = _descriptor.Descriptor(
  name='HeaderStatistics',
  full_name='proto.types.HeaderStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposeTime', full_name='proto.types.HeaderStatistics.proposeTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tentativeTime', full_name='proto.types.HeaderStatistics.tentativeTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='definiteTime', full_name='proto.types.HeaderStatistics.definiteTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tentative', full_name='proto.types.HeaderStatistics.tentative', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=448,
)


_BLOCKSTATISTICS = _descriptor.Descriptor(
  name='BlockStatistics',
  full_name='proto.types.BlockStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposeTime', full_name='proto.types.BlockStatistics.proposeTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=488,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='proto.types.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.types.Block.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.types.Block.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.types.Block.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bst', full_name='proto.types.Block.bst', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=657,
)

_BLOCKHEADER.fields_by_name['m'].message_type = spinnerTypes_dot_meta__pb2._META
_BLOCKHEADER.fields_by_name['bid'].message_type = _BLOCKID
_BLOCKHEADER.fields_by_name['hst'].message_type = _HEADERSTATISTICS
_BLOCK.fields_by_name['header'].message_type = _BLOCKHEADER
_BLOCK.fields_by_name['id'].message_type = _BLOCKID
_BLOCK.fields_by_name['data'].message_type = spinnerTypes_dot_transaction__pb2._TRANSACTION
_BLOCK.fields_by_name['bst'].message_type = _BLOCKSTATISTICS
DESCRIPTOR.message_types_by_name['BlockID'] = _BLOCKID
DESCRIPTOR.message_types_by_name['BlockHeader'] = _BLOCKHEADER
DESCRIPTOR.message_types_by_name['HeaderStatistics'] = _HEADERSTATISTICS
DESCRIPTOR.message_types_by_name['BlockStatistics'] = _BLOCKSTATISTICS
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK

BlockID = _reflection.GeneratedProtocolMessageType('BlockID', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKID,
  __module__ = 'spinnerTypes.block_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.BlockID)
  ))
_sym_db.RegisterMessage(BlockID)

BlockHeader = _reflection.GeneratedProtocolMessageType('BlockHeader', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKHEADER,
  __module__ = 'spinnerTypes.block_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.BlockHeader)
  ))
_sym_db.RegisterMessage(BlockHeader)

HeaderStatistics = _reflection.GeneratedProtocolMessageType('HeaderStatistics', (_message.Message,), dict(
  DESCRIPTOR = _HEADERSTATISTICS,
  __module__ = 'spinnerTypes.block_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.HeaderStatistics)
  ))
_sym_db.RegisterMessage(HeaderStatistics)

BlockStatistics = _reflection.GeneratedProtocolMessageType('BlockStatistics', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKSTATISTICS,
  __module__ = 'spinnerTypes.block_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.BlockStatistics)
  ))
_sym_db.RegisterMessage(BlockStatistics)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'spinnerTypes.block_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.Block)
  ))
_sym_db.RegisterMessage(Block)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013proto.typesB\005block'))
# @@protoc_insertion_point(module_scope)
