# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spinnerTypes/client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spinnerTypes import transaction_pb2 as spinnerTypes_dot_transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spinnerTypes/client.proto',
  package='proto.types',
  syntax='proto3',
  serialized_pb=_b('\n\x19spinnerTypes/client.proto\x12\x0bproto.types\x1a\x1espinnerTypes/transaction.proto\"0\n\x08TxStatus\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.proto.types.TxState\"F\n\x05TxReq\x12\x1e\n\x03tid\x18\x01 \x01(\x0b\x32\x11.proto.types.TxID\x12\x10\n\x08\x62locking\x18\x02 \x01(\x08\x12\x0b\n\x03\x63id\x18\x03 \x01(\x05\"9\n\x08\x42lockReq\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\x10\n\x08\x62locking\x18\x02 \x01(\x08\x12\x0b\n\x03\x63id\x18\x03 \x01(\x05\"\x19\n\nValidators\x12\x0b\n\x03ips\x18\x01 \x03(\t\"\x80\x01\n\nConfigInfo\x12\x13\n\x0b\x63lusterSize\x18\x01 \x01(\x05\x12\x13\n\x0bmaxFailures\x18\x02 \x01(\x05\x12\x0f\n\x07workers\x18\x03 \x01(\x05\x12\x0f\n\x07initTmo\x18\x04 \x01(\x05\x12\x14\n\x0cmaxTxInBlock\x18\x05 \x01(\x05\x12\x10\n\x08serverID\x18\x06 \x01(\x05*@\n\x07TxState\x12\r\n\tCOMMITTED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0c\n\x08PROPOSED\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\x42\r\n\x0bproto.typesb\x06proto3')
  ,
  dependencies=[spinnerTypes_dot_transaction__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TXSTATE = _descriptor.EnumDescriptor(
  name='TxState',
  full_name='proto.types.TxState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMITTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROPOSED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=413,
  serialized_end=477,
)
_sym_db.RegisterEnumDescriptor(_TXSTATE)

TxState = enum_type_wrapper.EnumTypeWrapper(_TXSTATE)
COMMITTED = 0
PENDING = 1
PROPOSED = 2
UNKNOWN = 3



_TXSTATUS = _descriptor.Descriptor(
  name='TxStatus',
  full_name='proto.types.TxStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.types.TxStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=122,
)


_TXREQ = _descriptor.Descriptor(
  name='TxReq',
  full_name='proto.types.TxReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='proto.types.TxReq.tid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blocking', full_name='proto.types.TxReq.blocking', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='proto.types.TxReq.cid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=194,
)


_BLOCKREQ = _descriptor.Descriptor(
  name='BlockReq',
  full_name='proto.types.BlockReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='proto.types.BlockReq.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blocking', full_name='proto.types.BlockReq.blocking', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='proto.types.BlockReq.cid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=253,
)


_VALIDATORS = _descriptor.Descriptor(
  name='Validators',
  full_name='proto.types.Validators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ips', full_name='proto.types.Validators.ips', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=280,
)


_CONFIGINFO = _descriptor.Descriptor(
  name='ConfigInfo',
  full_name='proto.types.ConfigInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterSize', full_name='proto.types.ConfigInfo.clusterSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxFailures', full_name='proto.types.ConfigInfo.maxFailures', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workers', full_name='proto.types.ConfigInfo.workers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initTmo', full_name='proto.types.ConfigInfo.initTmo', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxTxInBlock', full_name='proto.types.ConfigInfo.maxTxInBlock', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverID', full_name='proto.types.ConfigInfo.serverID', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=411,
)

_TXSTATUS.fields_by_name['status'].enum_type = _TXSTATE
_TXREQ.fields_by_name['tid'].message_type = spinnerTypes_dot_transaction__pb2._TXID
DESCRIPTOR.message_types_by_name['TxStatus'] = _TXSTATUS
DESCRIPTOR.message_types_by_name['TxReq'] = _TXREQ
DESCRIPTOR.message_types_by_name['BlockReq'] = _BLOCKREQ
DESCRIPTOR.message_types_by_name['Validators'] = _VALIDATORS
DESCRIPTOR.message_types_by_name['ConfigInfo'] = _CONFIGINFO
DESCRIPTOR.enum_types_by_name['TxState'] = _TXSTATE

TxStatus = _reflection.GeneratedProtocolMessageType('TxStatus', (_message.Message,), dict(
  DESCRIPTOR = _TXSTATUS,
  __module__ = 'spinnerTypes.client_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.TxStatus)
  ))
_sym_db.RegisterMessage(TxStatus)

TxReq = _reflection.GeneratedProtocolMessageType('TxReq', (_message.Message,), dict(
  DESCRIPTOR = _TXREQ,
  __module__ = 'spinnerTypes.client_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.TxReq)
  ))
_sym_db.RegisterMessage(TxReq)

BlockReq = _reflection.GeneratedProtocolMessageType('BlockReq', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKREQ,
  __module__ = 'spinnerTypes.client_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.BlockReq)
  ))
_sym_db.RegisterMessage(BlockReq)

Validators = _reflection.GeneratedProtocolMessageType('Validators', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATORS,
  __module__ = 'spinnerTypes.client_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.Validators)
  ))
_sym_db.RegisterMessage(Validators)

ConfigInfo = _reflection.GeneratedProtocolMessageType('ConfigInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGINFO,
  __module__ = 'spinnerTypes.client_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.ConfigInfo)
  ))
_sym_db.RegisterMessage(ConfigInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013proto.types'))
# @@protoc_insertion_point(module_scope)
