# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spinnerTypes/transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spinnerTypes/transaction.proto',
  package='proto.types',
  syntax='proto3',
  serialized_pb=_b('\n\x1espinnerTypes/transaction.proto\x12\x0bproto.types\"G\n\x04TxID\x12\x12\n\nproposerID\x18\x01 \x01(\x05\x12\x0b\n\x03\x62id\x18\x02 \x01(\x05\x12\r\n\x05txNum\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"L\n\x0bTransaction\x12\x10\n\x08\x63lientID\x18\x01 \x01(\x05\x12\x1d\n\x02id\x18\x02 \x01(\x0b\x32\x11.proto.types.TxID\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x42\r\n\x0bproto.typesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TXID = _descriptor.Descriptor(
  name='TxID',
  full_name='proto.types.TxID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposerID', full_name='proto.types.TxID.proposerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid', full_name='proto.types.TxID.bid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='txNum', full_name='proto.types.TxID.txNum', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='proto.types.TxID.channel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=118,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='proto.types.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='proto.types.Transaction.clientID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.types.Transaction.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.types.Transaction.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=196,
)

_TRANSACTION.fields_by_name['id'].message_type = _TXID
DESCRIPTOR.message_types_by_name['TxID'] = _TXID
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION

TxID = _reflection.GeneratedProtocolMessageType('TxID', (_message.Message,), dict(
  DESCRIPTOR = _TXID,
  __module__ = 'spinnerTypes.transaction_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.TxID)
  ))
_sym_db.RegisterMessage(TxID)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'spinnerTypes.transaction_pb2'
  # @@protoc_insertion_point(class_scope:proto.types.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013proto.types'))
# @@protoc_insertion_point(module_scope)
